# Generated by Django 5.1.4 on 2025-02-26 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanScreen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
