# Generated by Django 5.1.4 on 2025-02-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanScreen', '0002_card_date_of_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='position_in_column',
        ),
        migrations.AlterField(
            model_name='card',
            name='prioridade',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Média'), ('BAIXA', 'Baixa')], default='', max_length=100),
        ),
    ]
